---
version: '3'
services:
  ft_jupyterlab:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter # Path to Dockerfile
    restart: unless-stopped
    container_name: cyft_trader_jupyter # Your customed container name
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "../user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      jupyter lab --port=8888 --ip 0.0.0.0 --allow-root